use std::error::Error;

pub fn run() -> Result<String, Box<Error>> {
    Ok("ok".to_owned())
}
